# Generated by Django 5.1.1 on 2024-09-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=60),
        ),
    ]
