# Generated by Django 5.1.1 on 2024-09-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frf', '0003_alter_enrollment_course_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='user',
            new_name='professor',
        ),
    ]
