# Generated by Django 5.1.1 on 2024-09-12 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frf', '0004_rename_user_professor_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='frf.faculty'),
        ),
    ]
