# Generated by Django 5.1.1 on 2024-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frf', '0005_alter_professor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
